FROM jupyter/datascience-notebook:python-3.9.6

RUN pip install --upgrade pip && pip install \
    deap update_checker tqdm stopit xgboost \
    dask[delayed] dask[dataframe] dask-ml fsspec>=0.3.3 distributed>=2.10.0 \
    scikit-mdr skrebate \
    tpot
